# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='class_name')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
        ),
    ]
